var MSG = {
  lang: "en",
  catLoadingBlocks: "Loading...",
  update: "update 2017.11.01",
  title: "Webduino Blockly",
  documentTitle: "Webduino Blockly ( Cloud )",
  editing: "",
  gotoTutorials: "Tutorials",
  gotoWebSite: "Official site",
  cleanUpBlocks: "Clean Up Blocks",
  exportImage: "Download Image",
  userMenuDashboard: "Dashboard",
  userMenuTutorials: "Tutorials",
  userMenuApiDocs: "API Docs",
  userMenuWebSite: "Home",
  userMenuLogout: "Logout",
  blocks: "Blocks",
  copyToClipboard: "Copy to Clipboard",
  changesSaved: "Changes Saved",
  linkTooltip: "Save and Link to Blocks",
  qrcodeTooltip: "Generate preview QR code",
  runTooltip: "Run Blocks in the Workspace",
  stopRunTooltip: "Stop running",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard All Blocks",
  sampleTooltip: "Load Sample Blocks",
  demoTooltip: "Web Demo Area",
  openJsbin: "Open Code Editor",
  checkDeviceOnline: "Check Device Status",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catExec: "Delay",
  catRepeat: "Repeat",
  catBoardGroup: "Board Control",
  catBoard: "Board",
  catPin: "I/O Pins",
  catLed: "LED",
  catRelay: "Relay",
  catRGBLed: "RGB LED",
  catUltraSonic: "Ultra Sonic",
  catSmartServo: "Smart Servo",
  catDht: "DHT",
  catG3: "G3",
  catButton: "Button Switch",
  catShock: "Shake Switch",
  catPir: "PIR Motion",
  catSound: "Sound Sensor",
  catBuzzer: "Buzzer",
  catServo: "Servo Motor",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Unable to load file. It may contains corrupted or unknown block.",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  catDataTransfer: "Data Transfer",
  catConsole: "Console",
  catMathOther: "Math Conversion",
  catTextLogic: "Text Logic",
  backIndex: "Webduino Blockly Tutorials",
  demoTitle: "Blockly Demo Area",
  catTutorials: "Blockly",
  linkToBin: "Let's Coding",
  catDatabase: "Database",
  catFirebase: "Firebase",
  catGoogleSheets: "Google Sheets",
  catCarTest: "Car",
  catBasic: "Basic Blocks",
  catWebduino: "Webduino Blocks",
  catMenu1: "Luminous",
  catMenu2: "Input/Output",
  catMenu3: "Environmental",
  catMenu4: "Wireless",
  catMenu5: "Toy/Motor",
  catSpeech: "Voice Control",
  catSpeak: "Speech",
  catMobile: "Mobile",
  catTracking: "Tracking",
  catKeyCode: "Keyboard",
  catPlus: "Advanced",
  catStandard: "Standard",
  catMax7219: "LED Matrix",
  catMP3: "MP3 Player",
  catSSD1306: "OLED Display",
  catPhotocell: "Photocell/Potentiometer",
  catSoil: "Soil Moisture",
  catIRRecv: "IR Recv",
  catIRLed: "IR Send",
  catADXL345: "ADXL345",
  catHX711: "Electronic Scales",
  catBarcode: "Barcode Scanner",
  catRFID: "RFID",
  catJoystick: "Joystick",
  catDemo: "Web Demo",
  catDemoText: "Show Text",
  catDemoLight: "Click Bulb",
  catDemoImage: "Control Image",
  catDemoChart: "Chart",
  catDemoArea: "Area Color",
  catDemoButton: "Click Button",
  catDemoRange: "Slider",
  catDemoYoutube: "YouTube",
  catDemoTracking: "Tracking",
  catDemoController: "Remote",
  demoAreaTitle: "Web Demo",
  demoAreaChoose: "Choose:",
  demoAreaSelect1: "Show Text",
  demoAreaSelect2: "Click Bulb",
  demoAreaSelect3: "Control Image",
  demoAreaSelect4: "Area Color",
  demoAreaSelect5: "Click Button",
  demoAreaSelect6: "Slider",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "Tracking",
  demoAreaSelect9: "Remote",
  demoAreaSelect10: "Chart",
  demoAreaColor: "Choose color: ",
  demoAreaBtn1: "Button 1",
  demoAreaBtn2: "Button 2",
  demoAreaBtn3: "Button 3",
  demoAreaBtn4: "Button 4",
  demoAreaBtn5: "Button 5",
  demoAreaSlider: "Slider: ",
  demoAreaSliderValue: "Value: ",
  demoAreaYoutube1: "YouTube video is displayed at the top",
  demoAreaYoutube2: "Must import: ",
  demoAreaRemoteDisplay: "Display",
  samples1:"Basic Samples",
  samples1_1:"LED",
  samples1_2:"RGB LED",
  samples1_3:"Buzzer",
  samples1_4:"Servo Motor",
  samples1_5:"LED Matrix",
  samples2:"Sensors",
  samples2_1:"Ultra Sonic",
  samples2_2:"DHT",
  samples2_3:"Sound Sensor",
  samples2_4:"PIR Motion",
  samples2_5:"PhotoCell",
  samples2_6:"Soil Moisture",
  samples2_7:"ADXL 345",
  samples2_8:"RFID",
  samples3:"I/O",
  samples3_1:"2 LED",
  samples3_2:"RGB LED",
  samples4:"Youtube",
  samples4_1:"RFID + Youtube",
  samples4_2:"Button + Youtube",
  samples4_3:"Ultra Sonic + Youtube",
  samples5:"Advanced",
  samples5_1:"Virtual Remote",
  samples5_2:"Speech + Bulb",
  samples5_3:"Face + Bulb",
  samples5_4:"Parking Sensors",
  samples5_5:"Toycar (keyboard)",
  samples5_6:"Toycar (Remote)",
  samples5_7:"DHT + Firebase",
  samples5_8:"RFID + Firebase",
  samples5_9:"DHT + LED Matrix",
  samples5_10:"Alarm",
  samples6:"Multiple Boards",
  samples6_1:"Soil Moisture + LED",
  samples6_2:"Ultra Sonic + LED Matrix",
  tabEnableBlocks: "Choose Blocks",
  tabExport: "Backup",
  tabCustom: "Load Custom Block",
  enableBlocksTitle: "Choose blocks to enable / disable",
  customBlockRemove: "Remove",
  customBlockAdd: "Add",
  customBlockInvalid: "The file is invalid.",
  customBlockNotFound: "Can not find the file, please make sure link is valid.",
  customBlockUnknownError: "Unknown error occured while loading the file, please make sure link is valid.",
  customBlockLinkInvalid: "The link is invalid, please make sure link is valid.",
  customBlockMIMEInvalid: "The file can't be use, please make sure MIME type is correct.",
  customBlockInUse: "Can not remove block(s) which is in use.",
  customBlockImportSuccess: "Imported block is ready to use.",
  customBlockRemoveSuccess: "Block removed.",
  importTitle: "Import",
  importButton: "Import",
  chooseFileButton: "Choose file",
  importFromUrlButton: "Import from URL",
  importUrlText: "Enter exported URL from trail version of Blockly",
  importDescription: "Import saved project.",
  importWarning: "This will override current project, do you wish to continue?",
  importInvalid: "Imported file is invalid.",
  exportTitle: "Export",
  exportDescription: "Export and download current project.",
  exportButton: "Export",
  customTitle: "Load Custom Block",
  customButton: "Load",
  customDescription: "Enter URL to block definition %1, and notice the followings:",
  customNotice1: "Make sure URL is valid. URL must use HTTPS.",
  customNotice2: "Pay attention to file %1 type. Consider using %2 if file is hosted on GitHub",
  customNotice3: "Make sure code is bug-free.",
  customeBlockAccessDenied: "Can't remove custom block from shared project, please clone the project and try again.",
  codeJsChangeFileName: "Change Filename",
  bootInitError: "The project is not existed or shared.",
  blockToJsFailed: "Parsed blocks to javascript failed",
  bootInitUnknownError: "Loading data failed and will redirect to dashboard.",
  loadBlocksFailed: "The problem occurred while Loading data of custom blocks. Please check the file or remove it. ( %1 )"
};
