var MSG = {
  lang: "zh-hans",
  catLoadingBlocks: "载入积木",
  update: "update 2017.11.01",
  title: "Webduino Blockly",
  documentTitle: "Webduino Blockly ( Cloud )",
  editing: "",
  gotoTutorials: "教学范例",
  gotoWebSite: "官方网站",
  cleanUpBlocks: "整理积木",
  exportImage: "下载图片",
  userMenuDashboard: "专案",
  userMenuTutorials: "教学",
  userMenuApiDocs: "API 文件",
  userMenuWebSite: "首页",
  userMenuLogout: "登出",
  blocks: "积木",
  copyToClipboard: "复制到剪贴簿",
  changesSaved: " ( 已储存变更 )",
  linkTooltip: "储存并产生连结",
  qrcodeTooltip: "产生即时预览 QR code",
  runTooltip: "执行程序",
  stopRunTooltip: "停止执行",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行数",
  trashTooltip: "删除所有积木",
  sampleTooltip: "载入范例积木",
  demoTooltip: "网页互动区域",
  openJsbin: "打开程序编辑",
  checkDeviceOnline: "检查装置状态",
  catLogic: "逻辑",
  catLoops: "回圈",
  catMath: "数学式",
  catText: "文字",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变数",
  catFunctions: "流程",
  catExec: "等待",
  catRepeat: "状态切换",
  catBoardGroup: "开发板控制",
  catBoard: "开发板",
  catPin: "I/O 脚位",
  catLed: "LED 灯",
  catRelay: "继电器",
  catRGBLed: "三色 LED",
  catUltraSonic: "超音波",
  catSmartServo: "智慧伺服马达",
  catDht: "温湿度",
  catG3: "细悬浮微粒",
  catButton: "按钮开关",
  catShock: "震动开关",
  catPir: "人体红外线",
  catSound: "声音侦测",
  catBuzzer: "蜂鸣器",
  catServo: "伺服马达",
  listVariable: "列表",
  textVariable: "文字",
  httpRequestError: "命令出现错误。",
  linkAlert: "透过此连结分享您的积木组：\n\n%1",
  hashError: "对不起，「%1」并未对应任何已保存的程序。",
  xmlError: "档案已损毁或含有未知积木，故无法载入。",
  badXml: "解析 XML 时出现错误：\n%1\n\n选择'确定'以放弃您的更改，或选择'取消'以进一步编辑 XML。",
  catDataTransfer: "资料传输",
  catConsole: "控制台",
  catMathOther: "数值转换",
  catTextLogic: "文字逻辑",
  backIndex: "返回 Webduino 积木教学",
  demoTitle: "Blockly 范例测试区",
  catTutorials: "教学积木",
  linkToBin: "程序编辑",
  catDatabase: "资料库",
  catFirebase: "Firebase",
  catGoogleSheets: "Google 试算表",
  catCarTest: "自走车",
  catBasic: "基本积木",
  catWebduino: "Webduino 积木",
  catMenu1: "发光元件",
  catMenu2: "输入输出",
  catMenu3: "环境侦测",
  catMenu4: "无线感应",
  catMenu5: "玩具及马达",
  catSpeech: "语音声控",
  catSpeak: "语音朗读",
  catMobile: "行动装置",
  catTracking: "影像辨识",
  catKeyCode: "键盘行为",
  catPlus: "进阶功能",
  catStandard: "基本功能",
  catMax7219: "LED 点矩阵",
  catMP3: "MP3 播放器",
  catSSD1306: "OLED 萤幕",
  catPhotocell: "光敏(可变)电阻",
  catSoil: "土壤湿度侦测",
  catIRRecv: "红外线接收",
  catIRLed: "红外线发射",
  catADXL345: "三轴加速度计",
  catHX711: "电子磅秤",
  catBarcode: "条码机",
  catRFID: "RFID",
  catJoystick: "摇杆",
  catDemo: "网页互动",
  catDemoText: "显示文字",
  catDemoLight: "点击灯泡",
  catDemoImage: "控制图片",
  catDemoChart: "绘制图表",
  catDemoArea: "颜色调整",
  catDemoButton: "按钮行为",
  catDemoRange: "拉霸操作",
  catDemoYoutube: "YouTube",
  catDemoTracking: "影像追踪",
  catDemoController: "遥控器",
  demoAreaTitle: "网页互动区域",
  demoAreaChoose: "互动方式：",
  demoAreaSelect1: "显示文字",
  demoAreaSelect2: "点击灯泡",
  demoAreaSelect3: "控制图片",
  demoAreaSelect4: "颜色调整",
  demoAreaSelect5: "按钮行为",
  demoAreaSelect6: "拉霸操作",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "影像追踪",
  demoAreaSelect9: "遥控器",
  demoAreaSelect10: "绘制图表",
  demoAreaColor: "选择颜色：",
  demoAreaBtn1: "按钮 1",
  demoAreaBtn2: "按钮 2",
  demoAreaBtn3: "按钮 3",
  demoAreaBtn4: "按钮 4",
  demoAreaBtn5: "按钮 5",
  demoAreaSlider: "拉霸：",
  demoAreaSliderValue: "数值：",
  demoAreaYoutube1: "YouTube 影片会显示在上方",
  demoAreaYoutube2: "必须另外载入：",
  demoAreaRemoteDisplay: "显示",
  samples1: "基础操作",
  samples1_1: "LED",
  samples1_2: "全彩 LED",
  samples1_3: "蜂鸣器",
  samples1_4: "伺服马达",
  samples1_5: "LED 点矩阵",
  samples2: "传感器应用",
  samples2_1: "超音波侦测距离",
  samples2_2: "侦测环境温湿度",
  samples2_3: "侦测声音",
  samples2_4: "侦测人体红外线",
  samples2_5: "侦测环境光线",
  samples2_6: "侦测土壤湿度",
  samples2_7: "侦测三轴加速度",
  samples2_8: "侦测 RFID 识别码",
  samples3: "I/O 脚位",
  samples3_1: "操控两颗 LED",
  samples3_2: "操控全彩 LED",
  samples4: "Youtube 应用",
  samples4_1: "RFID 切换影片",
  samples4_2: "按钮开关控制播放",
  samples4_3: "超音波控制播放速度",
  samples5: "进阶应用",
  samples5_1: "网页虚拟遥控器",
  samples5_2: "声控电灯",
  samples5_3: "人脸追踪控制电灯",
  samples5_4: "倒车雷达",
  samples5_5: "自走车 ( 键盘 )",
  samples5_6: "自走车 ( 虚拟遥控器 )",
  samples5_7: "资料库记录温湿度",
  samples5_8: "RFID 简易门禁系统",
  samples5_9: "LED 点矩阵显示湿度",
  samples5_10: "闹钟 ( 蜂鸣器 + 点矩阵 )",
  samples6: "开发板连动",
  samples6_1: "土壤湿度 + LED",
  samples6_2: "超音波 + LED 点矩阵",
  tabEnableBlocks: "启用及停用",
  tabExport: "汇出及汇入",
  tabCustom: "使用自有积木",
  enableBlocksTitle: "选择启用积木",
  customBlockRemove: "移除",
  customBlockAdd: "加入",
  customBlockInvalid: "载入的档案有误",
  customBlockNotFound: "找不到指定档案，请确认连结是否正确",
  customBlockUnknownError: "载入档案时发生未知错误，请确认连结是否正确",
  customBlockLinkInvalid: "输入的连结有误，请确认连结是否正确",
  customBlockMIMEInvalid: "无法使用档案，请确定 MIME 类型是否正确",
  customBlockInUse: "积木使用中无法移除",
  customBlockImportSuccess: "汇入的积木已可使用",
  customBlockRemoveSuccess: "已移除指定积木",
  importTitle: "汇入",
  importButton: "汇入",
  chooseFileButton: "选择档案",
  importFromUrlButton: "由连结汇入...",
  importUrlText: "输入由体验版 Blockly 汇出的连结",
  importDescription: "汇入先前备份的专案",
  importWarning: "继续汇入将会复写目前的积木，确定要继续吗？",
  importInvalid: "汇入的档案格式有误",
  exportTitle: "汇出",
  exportDescription: "汇出目前专案的积木，并下载备份",
  exportButton: "汇出",
  customTitle: "使用自有积木",
  customButton: "汇入",
  customDescription: "请输入自有积木定义档 %1 连结，并注意下列事项",
  customNotice1: "确保连结有效，连结必须为安全连线 (HTTPS)",
  customNotice2: "注意档案 %1 类型，若档案位于 GitHub 可使用 %2",
  customNotice3: "检查程序码是否无误",
  customeBlockAccessDenied: "无法移除共享专案的自订积木，复制专案后才可进行编辑",
  codeJsChangeFileName: "变更档名",
  bootInitError: "专案不存在或此专案尚未公开分享!",
  blockToJsFailed: "积木解析失败",
  bootInitUnknownError: "载入资料发生错误，将转回导览页。",
  loadBlocksFailed: "载入自订积木时发生问题，请检查档案是否正确，或者将其移除 ( %1 )"
};
